version: "3"


services:
  app:
    image: ghcr.io/frank-iii/telegpt:master
    volumes:
      - ./config.json:/telegpt/config.json
      - ./data:/telegpt/data
    environment:
      - RUST_LOG=TRACE

  
